language: python
python: 3.6
before_install:
- ".travis/check_commit.sh"
install:
- pip install -e .[dev]
script:
- flake8
- make test
- make test/integration
deploy:
  provider: pypi
  user: __token__
  password:
    secure: foT2FMh27/NVhCsOvlajINVA73UqlIsUqREGTV6I0vjgOgTiHVJ3HN0ntdangAphVQR1qhHttzMImQSwaF4yiX26o/Lm2LjRMePis9otnaFeEy6Ez8XJTuHs57XnP+trwhCaUes7mEi6g/MPAIbEGBRrin2HmKRFh4LduNhclkvnEN78K1khm6ENlLrs3HjPTcxhZi96oJUQPmdJqRFHEh1sNp7DILCxIhf7NSWjjOxRxT726Km0kY/TcW/pdRiNyy3fKvBtA9XfI1DJGeRVNQ3HCPz9Yw02usiUBkugtgAWX17N/6SWvPbystUHKE1sn+LWS9DhtHHuyY9lojslSadrZHZR+dHzu+IFTOLWpdNtnmiH68tJqJKdDTPSQQ8v9Agrrc6vloek10artQOF6OorCGGE+hOUlP6qrgEz2YmklwcIN8Q/pWbp2srrD8gXf42nWOzKlZIeBh7BPgYQCL5erI6oyaVcCaPeJ+SDpPW0O3T1aqI4yd4YzA+XgYPAwIWPcWQyfi6lMbSIwwdvICBu9NG7Vb7U+2OoO6srzcNL/dKaSRYeeWT/4JJyPv23+0lDg91Fz0kwV/S20apCTtXAC5VqfnDjD/eE3cXKA49wyWWRh2D16z5ndYVG3t3WtGnuNmRMsapTFGqsp1TqZ+SYXIiC6J5MJkLp+qPS/ws=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
    branch: master
